FROM node:12

WORKDIR /var/www/

RUN git config --global user.email "jennifer@sinoluxfilm.com"
RUN git config --global user.name "XuanyiZhan"

# install global dependencies
RUN yarn global add gatsby-cli

# create new site
RUN gatsby new sinolux-site
WORKDIR /var/www/sinolux-site

# install project dependencies
RUN yarn add gh-pages --dev

# build and serve
RUN gatsby build && gatsby serve
