version: '3'
services:
  react-dev:
    build: .
    command: sh -c "yarn install && gatsby build && gatsby develop -H 0.0.0.0"
    ports:
      - '8000:8000'
    working_dir: /var/www/sinolux-site
    volumes:
      - .:/var/www/sinolux-site:cached
  react-prod:
    build: .
    command: sh -c "gatsby serve"
    working_dir: /var/www/sinolux-site
